### ISSUE TITLE
找不到名称tinymce

### ISSUE THREAD

**Issue by AmoZaul** [cooj/tinymce-vue3#3]
![image](https://user-images.githubusercontent.com/129259154/231077209-7d48ea13-2a8e-49f9-b61d-b733e8d52507.png)
Tinymce.vue的91行用了tinymce，但是报错这个没有定义

**Comment by nowo** [comment]
第一种，可以显示导入tinymce这个模块
```js
import tinymce from "tinymce";
```
第二种，改处理文件方法，不使用tinymce
![image](https://user-images.githubusercontent.com/70360040/231626614-af6a0b7e-4c60-49c4-bdef-5075f845d4b3.png)
这个在`vite-ts`分支下
